# Importing Data into R
library(readxl)
OnlineRetailData <- read_excel("~/Desktop/OnlineRetailData.xlsx", 
                               col_types = c("text", "text", "text", 
                                             "numeric", "date", "numeric", "numeric", 
                                             "text"))

# Importing libraries 
library(dplyr)
library(lubridate)
library(ggplot2)

# Head of the dataset
head(Online_Data, 3)
names(Online_Data)

" 
Using this we will define revenue as:
Revenue = Active Customer Count * Order Count * Average Revenue per Order

"

attach(OnlineRetailData)

# Monthly Revenue
# Multiplyng UnitPrice and Quantity to create a Revenue column

OnlineRetailData <- OnlineRetailData %>%
  mutate(Revenue = `UnitPrice`*`Quantity`)

# Grouping revenu by month to generate a plot
Monthly_Revenue <- OnlineRetailData %>%
  select(InvoiceDate, Revenue) %>%
  group_by(Date=floor_date(InvoiceDate, "month")) %>% # Grouping by months in type POSIXct
  summarise(Monthly_Revenue = sum(Revenue)) %>%  # Aggregating by Revenue
  order_by(Date)


# Plotting a graph line of Online Retailer Monthly Revenue
ggplot(data=Monthly_Revenue, aes(Date, Monthly_Revenue)) +
  geom_line(colour='darkblue') +
  geom_point() + 
  scale_y_continuous(labels = scales::dollar) + # Changing the Monthly_Revenue variable to Dollars
  labs(title='Monthly Revenue',
       y='Revenue')

# Calculating the percentage change and plotting it 
Perc_Change <- Monthly_Revenue %>%
  mutate(Percent_Change = (Monthly_Revenue/lag(Monthly_Revenue) - 1) * 100)  # Calculating the Percent Change 
  
# Plotting the percent change Monthly Revenue
ggplot(data=Perc_Change, aes(Date, Percent_Change)) +
  geom_line(colour='darkblue') +
  geom_point() +
  labs(title="Monthly Growth Rate",
       y='Percent Change')

# Monthly Active Users 
Total_MAU <- OnlineRetailData %>%
  mutate(Date=floor_date(InvoiceDate, "month")) %>%
  group_by(Date)  %>%
 summarise(MAU=n()) # Counting total number of users a month

Unique_MU <- OnlineRetailData %>%
  mutate(Date=floor_date(InvoiceDate, "month")) %>%
  group_by(Date)  %>%
  summarise(Unique_Active_Users=n_distinct(CustomerID)) # Selecting unique buyers a month 


# Plotting Monthly Active Users and Unique Active Users
MAU_line <- ggplot(data=Total_MAU, aes(Date, MAU)) +
  geom_line(colour='darkblue') +
  geom_point() +
  labs(title="Monthly Active Users",
       y='Users')
print(MAU_line)

# Nice upward trend!

# Plotting Unique Monthly Users
UM_line <- ggplot(data=Unique_MU, aes(Date, Unique_Active_Users)) +
  geom_line(colour='darkblue') +
  geom_point() +
  labs(title="Unique Active Users",
       y='Users')
print(UM_line)

# Nice upward trend of Unique Active Users! 

# Number of Unique Invoices a Month - Monthly Order Count
Monthly_Orders <- OnlineRetailData %>%
  mutate(Date=floor_date(InvoiceDate, "month")) %>%
  group_by(Date)  %>%
  summarise(Invoices=n_distinct(InvoiceNo)) # Selecting unique Invoice Number a month

Monthly_Order_line <- ggplot(data=Monthly_Orders, aes(Date,Invoices)) +
  geom_line(colour='darkblue') +
  geom_point() +
  labs(title="Total Number of Orders",
       y='Invoices')
print(Monthly_Order_line)

# Average Revenue per Order by Month
Revenue_per_Order <- OnlineRetailData %>%
  mutate(Date=floor_date(InvoiceDate, "month")) %>%
  group_by(Date) %>%
  summarise(Monthly_Revenue_Average = mean(Revenue))


# Build a bar graph for this Revenue per Order

# New Customer Ratio 
First_purchase <- OnlineRetailData %>%
  group_by(CustomerID) %>%
  mutate(Date=floor_date(InvoiceDate, "month"),First_Purchase= min(InvoiceDate),
         Type = case_when(InvoiceDate == First_Purchase ~'NEW', TRUE ~ 'EXISTING'))

New_vs_Existing_Revenue <- First_purchase %>%
  group_by(Date = floor_date(InvoiceDate, 'month'), Type) %>%
  summarise(Revenue = sum(Revenue))

# Ploting New vs Existing Revenue over month

ggplot(New_vs_Existing_Revenue, aes(Date, Revenue, col=Type)) + 
  geom_line() + 
  scale_y_continuous(labels = scales::dollar) 

# Interesting! New Customers revenue shows a decreasing trend, while existing customers trend revenue shows a strong and steady line

# Let's dig into new customer ratio. I wonder if we are not acquiring users or as fast or its'a  matter of revenue not generated by this users
# I would expect a decrease in user based. 

# Counting New Unique users per month
New_User_Ratio <-  First_purchase %>%
  filter(Type == 'NEW') %>%
  group_by(Date) %>%
  summarise(Number_New_Users = n_distinct(CustomerID))

All_Users_Month <- First_purchase %>%
  group_by(Date) %>%
  summarise(Total_Users= n_distinct(CustomerID))
  
New_Old_User_Ratio <- inner_join(New_User_Ratio, All_Users_Month) %>%
  mutate(Ratio = round((`Number_New_Users`/`Total_Users`)*100))

# Visualizing New Users Ratio

ggplot(New_Old_User_Ratio, aes(Date,Ratio))  +
  geom_text(aes(label = Ratio), vjust = -0.3) +
  geom_bar(stat = 'identity') +
  labs(title = 'New Monthly User Ratio') 

# Decreasing trend in New Monthly Users. 




  
  
  




                        
  
  







